services:
  back:
    build:
      context: ./backend
    restart: always

  front:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./webserver/templates:/etc/nginx/templates
      - ./webserver/app.conf:/etc/nginx/conf.d/app.conf
      - ./webserver/certs:/etc/certs
