services:
  back:
    image: marzboard/backend:latest
    build:
      context: ./backend
      target: "development"
    restart: always
    volumes:
      - ./backend:/app
      - ./nodes.json:/app/nodes.json

  front:
    image: marzboard/frontend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: "development"
    restart: always
    ports:
      - 3010:3010
    volumes:
      - ./frontend:/app

  server:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./webserver/dev.conf:/etc/nginx/conf.d/default.conf
    command: ["nginx", "-g", "daemon off;"]

  redis:
    image: redis:7
    restart: always
