services:
  back:
    image: marzboard/backend:latest
    build:
      context: ./backend
      target: "production"
    restart: always
    volumes:
      - ./nodes.json:/app/nodes.json
      - ./admins.json:/app/admins.json

  front:
    image: marzboard/frontend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: "production"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./webserver/prod.conf:/etc/nginx/conf.d/prod.conf
      - ./webserver/certs:/etc/certs

  redis:
    image: redis:7
    restart: always
